fixup! Cancel previous PR builds

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,7 +23,7 @@ concurrency:
 
 jobs:
   build-success:
-    if: ${{ !success() }} # if `failure()` would not work for cancellations
+    if: ${{ always() }}
     runs-on: ubuntu-latest
     needs:
       [
@@ -32,7 +32,12 @@ jobs:
         cs,
       ]
     steps:
-      - run: false
+      - name: "Check results"
+        run: |
+          set -x
+          echo '${{ needs.amt.result }}' | grep -x 'success|skipped' || { echo 'amt failed' >&2; exit 1; }
+          echo '${{ needs.b.result }}' | grep -x 'success|skipped' || { echo 'b failed' >&2; exit 1; }
+          echo '${{ needs.cs.result }}' | grep -x 'success|skipped' || { echo 'cs failed' >&2; exit 1; }
 
   amt:
     runs-on: ubuntu-latest
